### PR TITLE
Makefile for docker image build

### PR DESCRIPTION
**Pull request by squaremo**
This builds in three stages, to make a minimal image:
- make a container with the golang tools, suitable for making
  statically-linked executables;
- runs that to produce the executable file;
- build an image with the executable file and nothing else

### CODE REVIEW

**Comment by squaremo** [comment]
(Ah but it will need iptables in the image, unless it can be mounted)

**Comment by dpw** [comment]
> (Ah but it will need iptables in the image, unless it can be mounted)

Yeah.  I think we'll need to use alpine linux again.

(`docker build` has an `-f` option?!? How did I miss that?)

**Comment by squaremo** [comment]
I've amended it to use alpine linux. It still builds a static binary, because the shared libraries it wants (at least per my makefile, in which I use the golang docker image to build the binary) are different in alpine.

**Comment by dpw** [comment]
@bboreham didn't see your PR, and did https://github.com/bboreham/ambergris/commit/607e4c0a349cf5e36ab397bef590fc9105026b48

I like the containerized build, but I wonder if it runs into the file ownership issues I dealt with when doing the containerized build for weave.  I'll have to take a closer look.

Do we need to do a static build if we are starting with alpine linux anyway?

**Comment by squaremo** [comment]
> I like the containerized build, but I wonder if it runs into the file ownership issues I dealt with when doing the containerized build for weave.

Oh, what were those? Possibly it's best not to mix building on the host and building in the container, maybe that would lead to problems of that kind.

> Do we need to do a static build if we are starting with alpine linux anyway?

I simplified it to build a dynamic binary (in the golang image, based on debian I think), but it didn't like running it in the alpine image, so I went back to the static binary.

**Comment by dpw** [comment]
> > I like the containerized build, but I wonder if it runs into the file ownership issues I dealt with when doing the containerized build for weave.
> 
> Oh, what were those? Possibly it's best not to mix building on the host and building in the container, maybe that would lead to problems of that kind.

If stuff is running inside the container as root (which it normally does unless you make other arrangements), then any files it creates on a bind mount will also belong to root.  In the context of running a containerized go build, this can mean you end up with files owned by root scattered around your GOPATH.

There's an incantation in the weave containerized build script to work around that (and also uses of sudo in the Makefile): https://github.com/weaveworks/weave/blob/master/build/build.sh#L29

> ```
> Do we need to do a static build if we are starting with alpine linux anyway?
> ```
> 
> I simplified it to build a dynamic binary (in the golang image, based on debian I think), but it didn't like running it in the alpine image, so I went back to the static binary.

I think @bboreham had a dynamic binary working under alpine linux.  But his Dockerfile doesn't tell the whole story, so I'm not completely sure.

**Comment by squaremo** [comment]
> In the context of running a containerized go build, this can mean you end up with files owned by root scattered around your GOPATH.

I only bind-mount the current directory, into (the container's) $GOPATH/..../ambergris, so nothing except the output ends up being written to the host filesystem. That might still run into the problem you describe. It doesn't for me, but perhaps that's some side-effect of using a boot2docker/docker-machine VM (which does a directory share to make bind-mounts from the VM host work in the VM). Did you try it out and have this problem, or are you anticipating it?

> I think @bboreham had a dynamic binary working under alpine linux. But his Dockerfile doesn't tell the whole story, so I'm not completely sure.

Bryan's Dockerfile uses the binary assumed to be built in the current directory, so whether it works or not might depend on where you build it. It's certainly a simpler build if a dynamic binary will work -- perhaps you can help me figure that out tomorrow.

**Comment by dpw** [comment]
> Did you try it out and have this problem, or are you anticipating it?

Just anticipating it.  I have residual nervousness about things which mount subtrees of my home directory into containers.

But yes, if you are not mounting the whole GOPATH, less can go wrong.  But does that mean it needs to fetch dependencies on every build?

**Comment by squaremo** [comment]
> But yes, if you are not mounting the whole GOPATH, less can go wrong. But does that mean it needs to fetch dependencies on every build?

Yes; the latest commit mounts another directory for the dependencies to go in. For comparison:
- `go get` every time -> 1m30s
- `go get` into mounted directory -> 30s
- `go build` after a prior `go get` -> 23s

**Comment by dpw** [comment]
> Yes; the latest commit mounts another directory for the dependencies to go in.

Great.  (The dependencies on master now seem to include the whole of etcd.  I'm not quite sure why.)

**Comment by bboreham** [comment]
Possibly because I used a symbolic constant to replace the number `100`

**Comment by squaremo** [comment]
Now it should
- preserve the file ownership, so `make clean` doesn't need sudo
- make a static binary that can run in alpine

**Pull request merged**
